name: Analysis

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allows for manual triggering from the GitHub UI

permissions:
  contents: write  # Required for pushing changes to the repository

jobs:
  analysis:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up the Python environment
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run analysis script
        run: |
          python3 scripts/analysis.py  # Run your Python analysis script

      - name: Commit and push analysis results
        run: |
          git config --global user.name "GitHub Actions"  # Configure Git for committing
          git config --global user.email "actions@github.com"
          git add output_of_the_analysis/  # Add your output folder (e.g., analysis results) to Git
          git commit -m "Update analysis results"  # Commit the changes
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/Marketing-Data-Analysis-Portfolios-.git  # Use your personal token to push changes
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use your personal GitHub token for authentication
